# Generated by Django 5.0.1 on 2024-02-13 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_paradise', '0002_cheese_crust_sauce_size_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('delivery_address', models.TextField()),
                ('card_number', models.PositiveIntegerField()),
                ('card_expiry_date', models.DateField()),
                ('card_cvv', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
