# Generated by Django 5.0.1 on 2024-02-14 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_paradise', '0004_alter_order_card_cvv_alter_order_card_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
