# Generated by Django 5.0.1 on 2024-02-14 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_paradise', '0005_pizza_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
